- public/css/components/sections/_sponsors.scss
We want to set a default grow and shirnk of 1 so sponsors grow and
shrink as room is available.
In addition, we want to set flex-basis to 200px which is the minimum
size we want sponsors to be. This will allow the flex boxes to break and
go into multiple rows and eventually a column naturally.
> Use flex shorthand for sponsors.

- _harp/css/components/sections/_main-preview.scss
Make sure that anchor tags are available to be clicked on.
> Ignore pointer-events on hero-overlay.

- _harp/_users.ejs
Fix a syntax error in the videojs.com home page's HTML which was causing the [W3C HTML Validator to choke](https://validator.w3.org/nu/?doc=http%3A%2F%2Fvideojs.com%2F). Fixes #35.
> Fix a syntax error in the videojs.com home page (missing </a> end tag)

- _harp/css/components/sections/_main-preview.scss
- _harp/index.ejs
Avoids letterboxing at narrow screen sizes, and we just ought to use it really.
> Use fluid sizing

- _harp/_layout.ejs
- _harp/index.ejs
Anyone mind if I try out an error tracker or two on videojs.com? I'm interested to know what they can show, and what kind of playback errors we're seeing with the basic player.
I'm trying TrackJS first, but also want to try Sentry.
> Add an error tracker

- _src-js/index.js
- _src-js/lib/vjs-version.js
npmcdn.com is specifically made to return back npm package information in a CORS-accessible way.
```sh
$ curl -ILs http://npmcdn.com/video.js@latest/package.json
HTTP/1.1 301 Moved Permanently
Date: Fri, 15 Apr 2016 21:24:29 GMT
Location: https://npmcdn.com/video.js@latest/package.json
HTTP/1.1 302 Found
Date: Fri, 15 Apr 2016 21:24:29 GMT
Connection: keep-alive
Access-Control-Allow-Origin: *
Cache-Control: public, max-age=500
Location: /video.js@5.8.8/package.json
HTTP/1.1 200 OK
Date: Fri, 15 Apr 2016 21:24:30 GMT
Content-Type: application/json; charset=utf-8
Content-Length: 2860
Connection: keep-alive
Access-Control-Allow-Origin: *
Cache-Control: public, max-age=31536000
```
Also, there's a defaults version for both that if the request fails or the response fails to parse as JSON we …
> Use a default version number and try to get the latest from npmcdn

- _src-js/lib/vjs-version.js
We were making the requests against HTTP which returned a 301 redirect
to the HTTPS protocol. However, this didn't include CORS headers, so,
everything broke. I opened an issue with unpkg but it may not be
possible to fix, so, we should just use HTTPS.
See: https://github.com/unpkg/unpkg.com/issues/22.
> fix: always make requests to unpkg over HTTPS

- _harp/css/components/_affixed-sidebar.scss
This will prevent the nav bar from being overlapped by the pages content if the width is smaller than the content of said page. 
Issue:
https://videojs.slack.com/files/kreynolds/F6CVC2G3Y/screen_shot_2017-07-21_at_2.12.20_pm.png
> fix for .affixed-sidebar

- _harp/_data.json
- _harp/advanced/_data.json
We had previously locked videojs.com on a test version of the Mux integration for an extended test, and this change puts it back on the mainline release of [videojs-mux](https://docs.mux.com/docs/web-integration-guide?muxLang=Video.js).
> update Mux integration

- _src-js/advanced.js
- _src-js/home.js
litix.io is in the EasyPrivacy list. Where an ad blocker has blocked the mux plugin script, the player fails to initialise as the plugin defined in the player opts is not available. This moves mux initialisation to the ready callback and checks for its existence.
> move mux plugin to ready()

- _src-js/lib/playlist.js
Switch the Elephants Dream playback over to using the HLS stream we created which supports switchable audio description, captions, and subtitles. Keep support for Chapters via a separate text track.
> Use the Elephants Dream HLS video (with the MP4 and OGG videos as fall-back)

- _src-js/advanced.js
- _src-js/lib/playlist.js
Allow URLs with fragment identifiers to specify a particular video (e.g. https://videojs.com/advanced/#elephantsdream), so that specific videos can be bookmarked.
This PR allows fragment identifiers to be specified, and also adds the fragment identifier for the video currently being played to the URL in the browser, so that users can tell what the correct identifier for each video is.
> Support fragment identifier (e.g. #elephantsdream) in the URL of the Advanced page to specify a particular video from the playlist

- Gruntfile.js
- _harp/css/modules/_utility.scss
- _harp/index.ejs
- _src-js/home.js
- _src-js/lib/playlist.js
Temporary fix to add alt text to the npm shield image. As noted, the alt text eventually needs updating to reflect the same version information that is shown in the shields.io image.
> Add a text alternative for the npm shield image

- src/components/HomeComponents/AdvancedExample/index.jsx
- src/components/HomeComponents/Hero.jsx
- src/components/Player.jsx
Bug:
1. Open homepage on mobile safari
1. Play the video in the hero image
1. Safari's native full-screen video player pops out (expected)
1. Close Safari's native full-screen video player by tapping the "x" in the top left corner
1. Page is bugged out - video player is black, buttons under the video player disappear
FIx:
* add playsInline attribute to the `video` component in hero image
* also add playsInline attribute to the `video` component in the advanced example
There might be more videos that I missed that we want to add the attribute to but I think these are the only ones
---
See if you can repro this on production and then try my fix on the [deploy preview](https://deploy-preview-109--videojs-dot-com.netlify.com/)
> Mobile Safari bugfix: add playsInline attribute to home hero and advanced example

- src/components/Link.jsx
The extra weight makes the links stand out, but not too much (it is less than **Bold**).
> fix unreadable links #116

- package-lock.json
- package.json
> fix: downgrade to query-string@5 for IE11 support

- src/mdx-pages/guides/components.mdx
- src/mdx-pages/guides/faqs.mdx
- src/mdx-pages/guides/options.mdx
- src/mdx-pages/guides/player-workflows.mdx
This brings in changes from the following PRs:
- https://github.com/videojs/video.js/pull/7635
- https://github.com/videojs/video.js/pull/7609
- https://github.com/videojs/video.js/pull/7629
- https://github.com/videojs/video.js/pull/7647
- https://github.com/videojs/video.js/pull/7611
This captures all changes to `docs/guides/` in Video.js since they were initially imported into this repository.
There is a related PR here: https://github.com/videojs/video.js/pull/7706
> Sync guides with changes made in the main video.js repository since moving them here

- .nvmrc
Update `.nvmrc` file to use `lts/erbium` (node v12).
> chore: Update nvmrc to lts/erbium

- src/mdx-pages/guides/options.mdx
Adds the undocumented `id` option to the options guide.
Also moves `fullscreen` into alphabetical order.
Fixes videojs/video.js/issues/7670
> docs: Add id option

- src/components/AdvancedComponents/AdvancedHero.jsx
The Advanced Example page hero component was missed in the recent tag/style updates for [PR 136](https://github.com/videojs/videojs.com/pull/136) and this change corrects that omission.
**Changes include:**
- Remove the `h1` tag from the Hero component and update the headings/subheadings to use `h2` and `p` tags for accessibility.
- Style is standardized to match other Hero components with subheadings on the site.
> fix: Update Advanced Example page hero

- package-lock.json
- package.json
Fixes back navigation going to /.
This was [fixed in gatsby 2.19.5](https://github.com/gatsbyjs/gatsby/issues/8357#issuecomment-584551111) by upgrading its dependency @reach/router. Updating gatsby to that version isn't trivial, and the effort would probably be better spent on updating the major version, so as a quick fix this jsut updates @reach/router.
> fix: Fix back navigation

- src/mdx-pages/guides/components.mdx
Adds the example og component creation from the jsdoc directly into the component guide.
Mentions deprecation of `videojs.extend()` in anticipation of videojs/video.js#7761
> docs: Add examples of creating a component

- src/components/GettingStartedComponents/GettingStartedArticle.jsx
Importing the version JSON differently in #148 to remove a deprecation warning (`Should not import the named export 'version' (imported as 'version') from default-exporting module (only default export is available soon)`) broke the version number replacement in getting started.
> fix: fix version in getting started

- src/mdx-pages/guides/audio-tracks.mdx
More explicit statement about native browser lack of support for audio tracks.
> docs: Clarification to audio tracks doc

- src/mdx-pages/guides/options.mdx
Updates based on https://github.com/videojs/video.js/issues/7875
> docs(guides): click/doubleClick options don't work if controls:false

- src/components/CheckboxInput.jsx
- Hide inputs that are currently showing when checkbox labels are clicked 
- Enable checkboxes to be updated by clicking checkbox labels.
**Fixes** #161
> Fix: make checkbox labels clickable

- src/mdx-pages/guides/react.mdx
Update the `useEffect()` example to insert the player inside the provided element instead of usingt the provided element, because React strict mode's shenanigans with disposing and re-initialising the component don't play nice with Video.js's removal of the element on dispose.
> fix(docs): Update react guide for React 18

- src/mdx-pages/guides/options.mdx
change `userAction.doubleClick` to `userActions.doubleClick`
> docs: fix typo

- src/mdx-pages/guides/components.mdx
Updates the component guide documentation to provide guidance for extending video.js v8+ components/classes without the `extend()` function that are transpiled to ES5
> docs: ES5 class extension

- src/mdx-pages/guides/components.mdx
- src/mdx-pages/guides/options.mdx
- src/mdx-pages/guides/skins.mdx
Documents `useSVGIcons` player option for https://github.com/videojs/video.js/pull/8260
> docs: Add useSVGIcons option

- src/mdx-pages/guides/options.mdx
Documents the `playsinline` option introduced in videojs [6.1.0](https://github.com/videojs/video.js/releases/tag/v6.1.0).
Refers videojs/video.js#4348
> docs: add playsinline option

- src/mdx-pages/guides/options.mdx
Replace `pplayer` by `player`.
> docs: remove a typo from the responsive option

- src/components/WithMdxComponents.jsx
- Fix `getStringChild` function to return right value.
- Remove dotted lines around Link after clicking 
- Fix wrong header id
1. Go to /guides/setup
2. Click on `A Note on <video> Tag Attributes` in the Table of Contents
3. **Before fix**:  nothing happens. **After fix**:  it goes to `/guides/setup/#a-note-on-video-tag-attributes`
4. Also, click any header that has backticks( `` )   
for example,  <img width="217" alt="image" src="https://github.com/videojs/videojs.com/assets/57550290/ca12b056-1204-4b67-bc8b-ab5e7819bde5">
6. **Before fix**: it goes to `/guides/setup/#using-`. **After fix**: it goes to `/guides/setup/#using-videojs`
- Remove dotted lines around links
1. Go to  /guides/setup and scroll down
2. Click any header. For example "Manual Setup"
**Before fix**: dotted line shows …
> Fix wrong header ids on Guides

- src/mdx-pages/guides/options.mdx
Documents the `enableSmoothSeeking` option introduced in videojs 8.9.0.
Refers https://github.com/videojs/video.js/pull/8287
> docs: add enableSmoothSeeking option

- src/mdx-pages/guides/options.mdx
- src/mdx-pages/guides/picture-in-picture.mdx
Updates document picture in picture docs to remove reference to origin trial.
> fix: Document picture-in-picture is no longer behind an origin trial

- src/mdx-pages/getting-started.mdx
Google Analytics hasn't been used for so long now it doesn't make sense to keep this in
> fix: Remove note about Google Analytics

- download-plugins.js
The build script is failing as the plugins list is empty due to a change in NPM's search API behavior. This seems to be an [NPM bug](https://github.com/orgs/community/discussions/154222), so this is just a quick and hopefully temporary fix.
Changes search query to all packages tagged `videojs` rather than `videojs,videojs-plugin,videojs-skin`.
> fix: Change npm search as API response has changed
