- _harp/js/index.js
- _harp/js/plugins.js
- _src-js/plugins.js
Elsewhere there's been work done to automate the extension scraping. Hold off on pulling this in until we confirm what S3 bucket this is going to live in.
> updated to use extensions from s3

- _src-js/lib/vjs-version.js
> Use crossorigin.me and npm to get latest version

- _harp/_footer.ejs
- _harp/getting-started/index.ejs
- _harp/index.ejs
- _src-js/plugins.js
I thought I'd submitted this last year, but apparently not! Since I see there are changes happening in this repo, I thought I'd fix this niggling little validation error.
> Change mysterious "parent" in links to "target".

- _harp/_nav.ejs
> Add aria to github link

- _harp/index.ejs
> fix: protocol relative IGN embed

- _harp/_footer.ejs
- _harp/_nav.ejs
- _harp/_users.ejs
- _harp/advanced/index.ejs
- _harp/getting-started/index.ejs
- _harp/html5-video-support/index.ejs
- _harp/index.ejs
- _harp/mimes.html
Fixes https://github.com/videojs/videojs.com/pull/58
> https everywhere

- Gruntfile.js
- _harp/advanced/index.ejs
- package.json
Fixes https://github.com/videojs/video.js/issues/5358
> Upgrade playlist plugins

- _harp/html5-video-support/_data.json
- _harp/vendor/modernizr.js
Add a video-only modernizr custom build to vendor folder.
Fixes #97
> fix: current browser video support detection

- .nvmrc
- _src-js/lib/vjs-version.js
> fix: properly set default for videojs-ie8 version

- src/components/HomeComponents/Implementation.jsx
- src/components/Table.jsx
- src/pages/html5-video-support.jsx
Also added quite a bit of additional info and modern codecs.
> Add html5 video support table back. Closes #110.

- download-plugins.js
- package-lock.json
- package.json
- src/components/PluginsComponents/PluginsList.jsx
- src/components/PluginsComponents/PluginsListItem.jsx
- src/data/plugins.json
Also, paginate the plugins search query if necessary.
> feat: bring back downloads counts on plugins page

- src/mdx-pages/getting-started.mdx
> getting-started.md: comment out ie8 shim, change video.js to minfied version

- src/mdx-pages/guides/angular.mdx
- src/mdx-pages/guides/react.mdx
- src/mdx-pages/guides/vue.mdx
- src/mdx-pages/guides/webpack.mdx
This cleans up the guides for integrations for consistent language and grammar. It also cleans up code examples so they are clearer and follow patterns consistent with our general coding practices.
> Clean up integrations guides.

- package-lock.json
- src/components/BlogComponents/BlogHero.jsx
- src/components/GettingStartedComponents/GettingStartedHero.jsx
- src/components/GuidesComponents/GuidesHero.jsx
- src/components/Header.jsx
- src/components/Hero.jsx
- src/components/HomeComponents/AdvancedExample/index.jsx
- src/components/HomeComponents/Features.jsx
- src/components/HomeComponents/GetInvolved.jsx
- src/components/HomeComponents/Hero.jsx
- src/components/HomeComponents/Implementation.jsx
- src/components/HomeComponents/Sponsors.jsx
- src/components/HomeComponents/UsedBy.jsx
- src/components/HomeComponents/UsedByLogos.jsx
- src/components/PluginsComponents/PluginsHero.jsx
- src/components/SectionHeader.jsx
- src/pages/404.jsx
- src/pages/html5-video-support.jsx
- src/templates/HomeTemplate.jsx
Amend the homepage, header, and hero components' tags and composition for screen reader accessibility, heading hierarchy, and semantic clarity.
**Changes include:**
- `nav` element wrapper for desktop navigation `ul`.
- Refactor rendered Logo tags to use a screen reader legible `h1` tag.
- Logo component now includes the main `h1` element on the homepage.
- The logo image now uses the `a` tag directly, removing the need for an extra `div`.
- Amend Header style to use flex box column gaps instead of margin where appropriate.
- Remove `h1` from hero section and reconfigure text to use a single `h2` tag for legibility, while keeping the visual design.
- Page sections are updated to `section` tags with descriptive roles and aria labels.
- SectionHeaderTitle `h1` tags are bumped down to `h2` …
> refactor: Update homepage component and general header/hero elements

- src/mdx-pages/guides/components.mdx
Closes https://github.com/videojs/video.js/issues/7756
> fix(docs): Removed unnecessary components

- src/mdx-pages/guides/components.mdx
Corrected the visible text class name and made a few clarifications.
Separated out adding a compononent and creating a new one.
Fixes videojs/video.js#7759
> fix(docs): Update button examples in components doc

- src/mdx-pages/guides/options.mdx
- src/mdx-pages/guides/player-workflows.mdx
Depends on videojs/video.js/pull/7722
> docs: Add docs for `restoreEl` option

- src/mdx-pages/guides/react.mdx
Update react doc to address some issues that crept in when the docs were moved
Fixes videojs/video.js#7780
> fix(docs): Update react guide

- src/mdx-pages/guides/live.mdx
> fix(docs): Clarify seekToLiveEdge behavior

- src/mdx-pages/guides/options.mdx
Updates docs for skip forward/backward buttons from this pr: https://github.com/videojs/video.js/pull/8147
> docs: skip forward/backward buttons

- package-lock.json
- package.json
- src/components/HomeComponents/AdvancedExample/PlayerPlaylist.jsx
- src/components/HomeComponents/AdvancedExample/index.jsx
- src/components/HomeComponents/Hero.jsx
- src/mdx-pages/guides/options.mdx
- src/mdx-pages/guides/picture-in-picture.mdx
- src/templates/HomeTemplate.jsx
Documents `enableDocumentPictureInPicture` option for videojs/video.js/pull/8113
> feat: Add enablePictureInPicture option
